name: Generate and Deploy Javadocs

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allow reading repo contents and writing (for push)
      pages: write         # Allow writing to GitHub Pages
      id-token: write      # Allow OIDC token for authentication

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
        with:
          gradle-version: '9.0.0'

      - name: Extract Version from Gradle
        id: version
        run: |
          gradle clean
          version=$(gradle properties -q | grep "^version:" | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Display Version
        run: echo "Version is ${{ steps.version.outputs.version }}"

      - name: Generate Javadocs
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: gradle :core:aggregateJavadoc

      - name: Checkout gh-pages
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy versioned docs
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Deploying docs for version: $VERSION"
          
          cd gh-pages
          
          # Delete existing version folder if it exists
          rm -rf "$VERSION"
          
          # Create version directory
          mkdir -p "$VERSION"
          
          # Copy new docs to version folder
          cp -r ../core/build/docs/aggregateJavadoc/* "$VERSION"/
          
          # Update or create 'latest' to point to this version
          rm -rf latest
          cp -r "$VERSION" latest
          
          echo "Created version folder: $VERSION"
          echo "Updated latest to point to: $VERSION"

      - name: Generate versions.json
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: |
          cd gh-pages
          
          # Get all version directories (excluding 'latest' and any files)
          VERSIONS=$(find . -maxdepth 1 -type d \( -name "*.*.*" -o -name "v*" \) | sed 's|./||' | grep -v '^latest$' | grep -v '^\.$' | sort -V -r)
          
          echo "Found versions: $VERSIONS"
          
          # Generate versions.json
          echo "{" > versions.json
          echo '  "versions": [' >> versions.json
          first=true
          for version in $VERSIONS; do
            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> versions.json
            fi
            echo -n "    \"$version\"" >> versions.json
          done
          echo "" >> versions.json
          echo '  ],' >> versions.json
          echo "  \"latest\": \"${{ steps.version.outputs.version }}\"" >> versions.json
          echo '}' >> versions.json
          
          echo "Generated versions.json:"
          cat versions.json

      - name: Generate index.html
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: |
          cd gh-pages

          # Download the HTML template
          curl -s https://raw.githubusercontent.com/Jake-Moore/Jake-Moore.github.io/refs/heads/main/templates/index-template.html -o template.html

          # Create the dynamic content section in a separate file
          cat > dynamic_content.html << 'EOF'
          <h2>📚 Latest Version</h2>
          <a href="latest/" class="version-link latest">Latest (Recommended)</a>

          <h2>📋 All Versions</h2>
          <div id="versions" class="loading">Loading available versions...</div>

          <script>
          // Load versions
          fetch("versions.json")
              .then(response => {
                  if (!response.ok) throw new Error("Failed to load versions");
                  return response.json();
              })
              .then(data => {
                  const container = document.getElementById("versions");
                  container.innerHTML = "";
                  container.classList.remove("loading");

                  if (data.versions && data.versions.length > 0) {
                      data.versions.forEach(version => {
                          const link = document.createElement("a");
                          link.href = version + "/";
                          link.textContent = `Version ${version}`;
                          link.className = "version-link";
                          container.appendChild(link);
                      });
                  } else {
                      container.innerHTML = "<p>No versions available yet.</p>";
                  }
              })
              .catch(error => {
                  console.error("Error loading versions:", error);
                  document.getElementById("versions").innerHTML = 
                      "<p style=\"color: #dc3545;\">Error loading versions. Please refresh the page.</p>";
              });
          </script>
          EOF

          # Replace placeholders in the template
          sed "s|{{PAGE_TITLE}}|KamiCommon NMS Javadocs|g" template.html | \
          sed "s|{{PAGE_HEADING}}|🚀 KamiCommon NMS Javadocs|g" | \
          sed "s|{{PAGE_DESCRIPTION}}|Welcome to the KamiCommon NMS API documentation. Choose a version below to browse its Javadocs.|g" | \
          sed "s|{{GITHUB_PATH}}|/Jake-Moore/KamiCommonNMS|g" > temp_index.html

          # Replace the dynamic content placeholder
          awk '
          /{{DYNAMIC_CONTENT}}/ {
              while ((getline line < "dynamic_content.html") > 0) {
                  print line
              }
              close("dynamic_content.html")
              next
          }
          { print }
          ' temp_index.html > index.html

          # Clean up
          rm template.html temp_index.html dynamic_content.html

          echo "Generated index.html"

      - name: Commit and push
        if: "!endsWith(steps.version.outputs.version, 'SNAPSHOT')"
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📚 Deploy docs for v${{ steps.version.outputs.version }} - $(date)"
            git push
            echo "✅ Documentation deployed successfully!"
          fi